using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;

namespace MaxBotFA14.Model
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------



    // Type created for JSON at <<root>>
    [DataContract()]
    public partial class Races
    {

        [DataMember(Name = "event")]
        public string Event;

        [DataMember(Name = "schedule")]
        public Schedule Schedule;

        [DataMember(Name = "track")]
        public Track Track;
    }

    // Type created for JSON at <<root>> --> schedule
    [DataContract(Name = "schedule")]
    public partial class Schedule
    {

        [DataMember(Name = "Free practice 1")]
        public FreePractice1 Free_0020_practice_0020_1;

        [DataMember(Name = "Free practice 2")]
        public FreePractice2 Free_0020_practice_0020_2;

        [DataMember(Name = "Free practice 3")]
        public FreePractice3 Free_0020_practice_0020_3;

        [DataMember()]
        public Qualifying Qualifying;

        [DataMember()]
        public Race Race;
    }

    // Type created for JSON at <<root>> --> schedule --> Free practice 1
    [DataContract(Name = "Free practice 1")]
    public partial class FreePractice1
    {

        [DataMember()]
        public string date;

        [DataMember()]
        public string time_from;

        [DataMember()]
        public string time_to;
    }

    // Type created for JSON at <<root>> --> schedule --> Free practice 2
    [DataContract(Name = "Free practice 2")]
    public partial class FreePractice2
    {

        [DataMember()]
        public string date;

        [DataMember()]
        public string time_from;

        [DataMember()]
        public string time_to;
    }

    // Type created for JSON at <<root>> --> schedule --> Free practice 3
    [DataContract(Name = "Free practice 3")]
    public partial class FreePractice3
    {

        [DataMember()]
        public string date;

        [DataMember()]
        public string time_from;

        [DataMember()]
        public string time_to;
    }

    // Type created for JSON at <<root>> --> schedule --> Qualifying
    [DataContract()]
    public partial class Qualifying
    {

        [DataMember()]
        public string date;

        [DataMember()]
        public string time_from;

        [DataMember()]
        public string time_to;
    }

    // Type created for JSON at <<root>> --> schedule --> Race
    [DataContract()]
    public partial class Race
    {

        [DataMember()]
        public string date;

        [DataMember()]
        public string time_from;

        [DataMember()]
        public string time_to;
    }

    // Type created for JSON at <<root>> --> track
    [DataContract(Name = "track")]
    public partial class Track
    {

        [DataMemberAttribute()]
        public string description;

        [DataMember()]
        public string history;

        [DataMember()]
        public string qoute;
    }

}
